GET http://localhost:3000

### all songs with pagination
Get http://localhost:3000/songs/?page=1&limit=2

### all songs
Get http://localhost:3000/songs

### single song
Get http://localhost:3000/songs/2

### add song
Post http://localhost:3000/songs
Content-Type: application/json

{

    "releaseDate": "2025-02-11",
    "duration": "05:23",
    "title": "song 03",
    "artists": [1,2],
    "lyrics": "song number 03" 
}

### update song
Put http://localhost:3000/songs/3
Content-Type: application/json

{
"title": "You for Me 29",
"artists": ["Siagla", "Yan", "Ny"],
"releaseDate": "2022-09-30",
"duration": "02:45",
"lyrics": "Sby, you're my adrenaline."
}


### delete song
Delete http://localhost:3000/songs/2


### add playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
"name": "Feel Good Now",

"songs": [6],
"user": 1
}

### user signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"firstName": "samnew",
"lastName": "vin new",
"email": "sam111111@gmail.com",
"password": "12345"
}

### Login User

POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "sam12@gmail.com",
"password": "12345"
}

// "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbTEyQGdtYWlsLmNvbSIsImlkIjo1LCJpYXQiOjE3NDI1Mzc0OTgsImV4cCI6MTc0MjYyMzg5OH0.ENGyPCMMTdC_Vw7WFGKmri7Iib9ARvnxafoJP-I8oos"

### Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbTEyQGdtYWlsLmNvbSIsImlkIjo1LCJpYXQiOjE3NDI1Mzc1MzcsImV4cCI6MTc0MjYyMzkzN30.0ZUksyNipScPvmv_nqbtRNe_wgafZ8lJPz7KJ1y8eo4

